/*
 * Copyright © 2017 Samuel Holland <samuel@sholland.org>
 * SPDX-License-Identifier: GPL-2.0
 */

#ifndef PLATFORM_CCU_H
#define PLATFORM_CCU_H

#include <util.h>

#define CCU_GATE_BASE         0x0060

#define CCU_GATE_CE           BITFIELD_INDEX(0, 5)
#define CCU_GATE_DMA          BITFIELD_INDEX(0, 6)
#define CCU_GATE_MMC0         BITFIELD_INDEX(0, 8)
#define CCU_GATE_MMC1         BITFIELD_INDEX(0, 9)
#define CCU_GATE_MMC2         BITFIELD_INDEX(0, 10)
#define CCU_GATE_NAND         BITFIELD_INDEX(0, 13)
#define CCU_GATE_DRAM         BITFIELD_INDEX(0, 14)
#define CCU_GATE_EMAC         BITFIELD_INDEX(0, 17)
#define CCU_GATE_TSC          BITFIELD_INDEX(0, 18)
#define CCU_GATE_HSTIMER      BITFIELD_INDEX(0, 19)
#define CCU_GATE_SPI0         BITFIELD_INDEX(0, 20)
#define CCU_GATE_SPI1         BITFIELD_INDEX(0, 21)
#define CCU_GATE_USBOTG       BITFIELD_INDEX(0, 23)
#define CCU_GATE_EHCI0        BITFIELD_INDEX(0, 24)
#define CCU_GATE_EHCI1        BITFIELD_INDEX(0, 25)
#define CCU_GATE_EHCI2        BITFIELD_INDEX(0, 26)
#define CCU_GATE_EHCI3        BITFIELD_INDEX(0, 27)
#define CCU_GATE_OHCI0        BITFIELD_INDEX(0, 28)
#define CCU_GATE_OHCI1        BITFIELD_INDEX(0, 29)
#define CCU_GATE_OHCI2        BITFIELD_INDEX(0, 30)
#define CCU_GATE_OHCI3        BITFIELD_INDEX(0, 31)

#define CCU_GATE_VE           BITFIELD_INDEX(1, 0)
#define CCU_GATE_TCON0        BITFIELD_INDEX(1, 3)
#define CCU_GATE_TCON1        BITFIELD_INDEX(1, 4)
#define CCU_GATE_DEINTERLACE  BITFIELD_INDEX(1, 5)
#define CCU_GATE_CSI          BITFIELD_INDEX(1, 8)
#define CCU_GATE_TVE          BITFIELD_INDEX(1, 9)
#define CCU_GATE_HDMI         BITFIELD_INDEX(1, 11)
#define CCU_GATE_DE           BITFIELD_INDEX(1, 12)
#define CCU_GATE_GPU          BITFIELD_INDEX(1, 20)
#define CCU_GATE_MSGBOX       BITFIELD_INDEX(1, 21)
#define CCU_GATE_SPINLOCK     BITFIELD_INDEX(1, 22)

#define CCU_GATE_CODEC        BITFIELD_INDEX(2, 0)
#define CCU_GATE_SPDIF        BITFIELD_INDEX(2, 1)
#define CCU_GATE_PIO          BITFIELD_INDEX(2, 5)
#define CCU_GATE_THS          BITFIELD_INDEX(2, 8)
#define CCU_GATE_I2S0         BITFIELD_INDEX(2, 12)
#define CCU_GATE_I2S1         BITFIELD_INDEX(2, 13)
#define CCU_GATE_I2S2         BITFIELD_INDEX(2, 14)

#define CCU_GATE_I2C0         BITFIELD_INDEX(3, 0)
#define CCU_GATE_I2C1         BITFIELD_INDEX(3, 1)
#define CCU_GATE_I2C2         BITFIELD_INDEX(3, 2)
#define CCU_GATE_UART0        BITFIELD_INDEX(3, 16)
#define CCU_GATE_UART1        BITFIELD_INDEX(3, 17)
#define CCU_GATE_UART2        BITFIELD_INDEX(3, 18)
#define CCU_GATE_UART3        BITFIELD_INDEX(3, 19)
#define CCU_GATE_SCR0         BITFIELD_INDEX(3, 20)
#define CCU_GATE_SCR1         BITFIELD_INDEX(3, 21)

#define CCU_GATE_EPHY         BITFIELD_INDEX(4, 0)
#define CCU_GATE_DEBUG        BITFIELD_INDEX(4, 7)

#define CCU_RESET_BASE        0x02c0

#define CCU_RESET_CE          BITFIELD_INDEX(0, 5)
#define CCU_RESET_DMA         BITFIELD_INDEX(0, 6)
#define CCU_RESET_MMC0        BITFIELD_INDEX(0, 8)
#define CCU_RESET_MMC1        BITFIELD_INDEX(0, 9)
#define CCU_RESET_MMC2        BITFIELD_INDEX(0, 10)
#define CCU_RESET_NAND        BITFIELD_INDEX(0, 13)
#define CCU_RESET_DRAM        BITFIELD_INDEX(0, 14)
#define CCU_RESET_EMAC        BITFIELD_INDEX(0, 17)
#define CCU_RESET_TSC         BITFIELD_INDEX(0, 18)
#define CCU_RESET_HSTIMER     BITFIELD_INDEX(0, 19)
#define CCU_RESET_SPI0        BITFIELD_INDEX(0, 20)
#define CCU_RESET_SPI1        BITFIELD_INDEX(0, 21)
#define CCU_RESET_USBOTG      BITFIELD_INDEX(0, 23)
#define CCU_RESET_EHCI0       BITFIELD_INDEX(0, 24)
#define CCU_RESET_EHCI1       BITFIELD_INDEX(0, 25)
#define CCU_RESET_EHCI2       BITFIELD_INDEX(0, 26)
#define CCU_RESET_EHCI3       BITFIELD_INDEX(0, 27)
#define CCU_RESET_OHCI0       BITFIELD_INDEX(0, 28)
#define CCU_RESET_OHCI1       BITFIELD_INDEX(0, 29)
#define CCU_RESET_OHCI2       BITFIELD_INDEX(0, 30)
#define CCU_RESET_OHCI3       BITFIELD_INDEX(0, 31)

#define CCU_RESET_VE          BITFIELD_INDEX(1, 0)
#define CCU_RESET_TCON0       BITFIELD_INDEX(1, 3)
#define CCU_RESET_TCON1       BITFIELD_INDEX(1, 4)
#define CCU_RESET_DEINTERLACE BITFIELD_INDEX(1, 5)
#define CCU_RESET_CSI         BITFIELD_INDEX(1, 8)
#define CCU_RESET_TVE         BITFIELD_INDEX(1, 9)
#define CCU_RESET_HDMI0       BITFIELD_INDEX(1, 10)
#define CCU_RESET_HDMI1       BITFIELD_INDEX(1, 11)
#define CCU_RESET_DE          BITFIELD_INDEX(1, 12)
#define CCU_RESET_GPU         BITFIELD_INDEX(1, 20)
#define CCU_RESET_MSGBOX      BITFIELD_INDEX(1, 21)
#define CCU_RESET_SPINLOCK    BITFIELD_INDEX(1, 22)
#define CCU_RESET_DEBUG       BITFIELD_INDEX(1, 31)

#define CCU_RESET_EPHY        BITFIELD_INDEX(2, 2)

#define CCU_RESET_CODEC       BITFIELD_INDEX(4, 0)
#define CCU_RESET_SPDIF       BITFIELD_INDEX(4, 1)
#define CCU_RESET_PIO         BITFIELD_INDEX(4, 5)
#define CCU_RESET_THS         BITFIELD_INDEX(4, 8)
#define CCU_RESET_I2S0        BITFIELD_INDEX(4, 12)
#define CCU_RESET_I2S1        BITFIELD_INDEX(4, 13)
#define CCU_RESET_I2S2        BITFIELD_INDEX(4, 14)

#define CCU_RESET_I2C0        BITFIELD_INDEX(6, 0)
#define CCU_RESET_I2C1        BITFIELD_INDEX(6, 1)
#define CCU_RESET_I2C2        BITFIELD_INDEX(6, 2)
#define CCU_RESET_UART0       BITFIELD_INDEX(6, 16)
#define CCU_RESET_UART1       BITFIELD_INDEX(6, 17)
#define CCU_RESET_UART2       BITFIELD_INDEX(6, 18)
#define CCU_RESET_UART3       BITFIELD_INDEX(6, 19)
#define CCU_RESET_SCR0        BITFIELD_INDEX(6, 20)
#define CCU_RESET_SCR1        BITFIELD_INDEX(6, 21)

#endif /* PLATFORM_CCU_H */
